spring.application.name=backend
🐘 POSTGRESQL DATABASE CONFIGURATION
# ----------------------------------------
# The URL where your database lives 
spring.datasource.url=jdbc:postgresql://localhost:5432/credencedb

# Your database credentials (we will change the password in a moment)
spring.datasource.username=postgres
spring.datasource.password=root

# Tells Spring to automatically create or update our database tables based on our Java code
spring.jpa.hibernate.ddl-auto=update

# Prints the SQL queries in the terminal so we can see what is happening under the hood
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Specifies the exact database dialect
spring.jpa.open-in-view=false


# Python AI Microservice Configuration
ai.service.url=https://amirah-entodermic-melia.ngrok-free.dev/generate-report

#Add API password
app.api.key=hello

server.port=${PORT:8080}

